package Forms;

import javax.swing.JOptionPane;
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    public Home(String role) {
        initComponents();
        setLocationRelativeTo(null);
        if(role.equals("Cashier")){
            btnAddAccount.setVisible(false);
            btnAddProduct.setVisible(false);
            btnAddCategory.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAddAccount = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnAddCategory = new javax.swing.JButton();
        btnAddProduct = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnViewProducts = new javax.swing.JButton();
        btnSearchStockDetails = new javax.swing.JButton();
        btnSearchProductDetails = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAddAccount.setBackground(new java.awt.Color(255, 102, 102));
        btnAddAccount.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAddAccount.setForeground(new java.awt.Color(0, 0, 0));
        btnAddAccount.setText("Add Account");
        btnAddAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAccountActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 180, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("The Cosmetic Store");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 19, 403, 86));

        btnAddCategory.setBackground(new java.awt.Color(255, 102, 102));
        btnAddCategory.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAddCategory.setForeground(new java.awt.Color(0, 0, 0));
        btnAddCategory.setText("Add Category");
        btnAddCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCategoryActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, 180, -1));

        btnAddProduct.setBackground(new java.awt.Color(255, 102, 102));
        btnAddProduct.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAddProduct.setForeground(new java.awt.Color(0, 0, 0));
        btnAddProduct.setText("Add Product");
        btnAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProductActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 360, 180, -1));

        btnLogout.setBackground(new java.awt.Color(255, 102, 102));
        btnLogout.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(0, 0, 0));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 160, 180, -1));

        btnViewProducts.setBackground(new java.awt.Color(255, 102, 102));
        btnViewProducts.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnViewProducts.setForeground(new java.awt.Color(0, 0, 0));
        btnViewProducts.setText("View Product Details");
        btnViewProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewProductsActionPerformed(evt);
            }
        });
        getContentPane().add(btnViewProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 180, -1));

        btnSearchStockDetails.setBackground(new java.awt.Color(255, 102, 102));
        btnSearchStockDetails.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSearchStockDetails.setForeground(new java.awt.Color(0, 0, 0));
        btnSearchStockDetails.setText("Search Stock Details");
        btnSearchStockDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchStockDetailsActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearchStockDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 180, -1));

        btnSearchProductDetails.setBackground(new java.awt.Color(255, 102, 102));
        btnSearchProductDetails.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSearchProductDetails.setForeground(new java.awt.Color(0, 0, 0));
        btnSearchProductDetails.setText("Search Product Details");
        btnSearchProductDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchProductDetailsActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearchProductDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, 180, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagaes/Background.PNG"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCategoryActionPerformed
        // TODO add your handling code here:
        new ManageCategory().setVisible(true);
    }//GEN-LAST:event_btnAddCategoryActionPerformed

    private void btnAddAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAccountActionPerformed
        // TODO add your handling code here:
        new ManageAccount().setVisible(true);
    }//GEN-LAST:event_btnAddAccountActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you want to logout?" , "Select", JOptionPane.YES_NO_OPTION);
        if(a==0){
            setVisible(false);
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProductActionPerformed
        // TODO add your handling code here:
        new ManageProduct().setVisible(true);
    }//GEN-LAST:event_btnAddProductActionPerformed

    private void btnViewProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewProductsActionPerformed
        // TODO add your handling code here:
        new ViewProductDetails().setVisible(true);
    }//GEN-LAST:event_btnViewProductsActionPerformed

    private void btnSearchStockDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchStockDetailsActionPerformed
        // TODO add your handling code here:
        new SearchStockDetails().setVisible(true);
    }//GEN-LAST:event_btnSearchStockDetailsActionPerformed

    private void btnSearchProductDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchProductDetailsActionPerformed
        // TODO add your handling code here:
        new SearchProductDetails().setVisible(true);
    }//GEN-LAST:event_btnSearchProductDetailsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAccount;
    private javax.swing.JButton btnAddCategory;
    private javax.swing.JButton btnAddProduct;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSearchProductDetails;
    private javax.swing.JButton btnSearchStockDetails;
    private javax.swing.JButton btnViewProducts;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
